### ISSUE TITLE
Token value?

### ISSUE THREAD

**Issue by nielsbom** [mrsydster/T-Mobile-Go-Ulimited-Auto-Aanvuller#1]
Hi,

I'm on iOS and I think network sniffing is harder there.

[Here](https://gathering.tweakers.net/forum/list_messages/1755435) they say the Bearer Token is your phone number.
Can you confirm/deny this?

Thanks for the script in any case!

**Comment by mrsydster** [comment]
@nielsbom 

I am on Android. At least for Android I can confirm that the Bearer Token is not the phone number. 

Cheers

**Comment by nielsbom** [comment]
Thanks!

**Comment by tommiionfire** [comment]
On iphone you should install the CA cert from Burp suite, so it can decrypt the sniffed TLS traffic. 
https://portswigger.net/support/configuring-an-ios-device-to-work-with-burp
https://portswigger.net/support/installing-burp-suites-ca-certificate-in-an-ios-device

**Comment by nielsbom** [comment]
Thanks @tommiionfire I got that to work.

@mrsydster maybe an idea to update the README to state that the `xxxxx` are different values? I misunderstood that till I saw the network requests.

**Comment by mrsydster** [comment]
@nielsbom Done!

**Comment by nielsbom** [comment]
Sweet!
